apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- toYaml .Values.backend.labels | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.backend.labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.backend.labels | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.backend.name }}
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.service.targetPort }}
          name: http
          protocol: TCP
        env:
        - name: HOST
          value: {{ .Values.config.host | quote }}
        - name: PORT
          value: {{ .Values.backend.env.port | quote }}
        - name: YOLO_MODEL
          value: {{ .Values.config.yoloModel | quote }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.backend.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.backend.readinessProbe | nindent 10 }}
