apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- toYaml .Values.backend.labels | nindent 4 }}
  {{- if .Values.monitoring.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.backend.service.port }}"
    prometheus.io/path: "/metrics"
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- toYaml .Values.backend.labels | nindent 4 }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
    protocol: TCP
    name: http
