apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace.name }}
data:
  BACKEND_URL: "http://{{ .Values.backend.service.name }}:{{ .Values.backend.service.port }}/predict"
  YOLO_MODEL: {{ .Values.config.yoloModel | quote }}
  HOST: {{ .Values.config.host | quote }}
  BACKEND_PORT: {{ .Values.backend.service.port | quote }}
  FRONTEND_PORT: {{ .Values.frontend.service.targetPort | quote }}
