{{- if .Values.frontend.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.frontend.name }}-hpa
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- range $key, $val := .Values.frontend.labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.frontend.name }}
  minReplicas: {{ .Values.frontend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.frontend.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.frontend.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.frontend.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.frontend.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.frontend.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
  {{- if .Values.frontend.autoscaling.behavior }}
  behavior:
    {{- if .Values.frontend.autoscaling.behavior.scaleDown }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.frontend.autoscaling.behavior.scaleDown.stabilizationWindowSeconds }}
      policies:
      {{- range .Values.frontend.autoscaling.behavior.scaleDown.policies }}
      - type: {{ .type }}
        value: {{ .value }}
        periodSeconds: {{ .periodSeconds }}
      {{- end }}
      selectPolicy: {{ .Values.frontend.autoscaling.behavior.scaleDown.selectPolicy }}
    {{- end }}
    {{- if .Values.frontend.autoscaling.behavior.scaleUp }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.frontend.autoscaling.behavior.scaleUp.stabilizationWindowSeconds }}
      policies:
      {{- range .Values.frontend.autoscaling.behavior.scaleUp.policies }}
      - type: {{ .type }}
        value: {{ .value }}
        periodSeconds: {{ .periodSeconds }}
      {{- end }}
      selectPolicy: {{ .Values.frontend.autoscaling.behavior.scaleUp.selectPolicy }}
    {{- end }}
  {{- end }}
{{- end }}
