apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- toYaml .Values.frontend.labels | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.frontend.labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.frontend.labels | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.frontend.name }}
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.service.targetPort }}
          name: http
          protocol: TCP
        env:
        - name: BACKEND_URL
          value: "http://{{ .Values.backend.service.name }}:{{ .Values.backend.service.port }}/predict"
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.frontend.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.frontend.readinessProbe | nindent 10 }}
