{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.monitoring.grafana.service.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: grafana
    component: monitoring
spec:
  type: {{ .Values.monitoring.grafana.service.type }}
  selector:
    app: grafana
    component: monitoring
  ports:
  - port: {{ .Values.monitoring.grafana.service.port }}
    targetPort: {{ .Values.monitoring.grafana.service.targetPort }}
    protocol: TCP
    name: http
{{- end }}
